# Generated by Django 6.0.1 on 2026-01-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('fa-home', 'Home & Household'), ('fa-broom', 'Cleaning'), ('fa-bug', 'Pest Control'), ('fa-truck-moving', 'Movers & Logistics'), ('fa-couch', 'Interior Decor'), ('fa-car', 'Vehicle Services'), ('fa-spa', 'Beauty & Spa'), ('fa-cut', 'Barber/Haircut'), ('fa-hand-sparkles', 'Manicures'), ('fa-magic', 'Makeup'), ('fa-wrench', 'Plumbing & Repair'), ('fa-bolt', 'Electrical'), ('fa-tv', 'Electronics'), ('fa-plug', 'Appliances'), ('fa-cog', 'Mechanical'), ('fa-utensils', 'Catering'), ('fa-birthday-cake', 'Pastry'), ('fa-calendar-alt', 'Events'), ('fa-microphone', 'MC Services'), ('fa-camera', 'Photography'), ('fa-box', 'Deliveries'), ('fa-user-nurse', 'Health & Care'), ('fa-shield-alt', 'Security'), ('fa-leaf', 'Garden & Landscaping')], default='fa-home', help_text='Select a professional icon for this category', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL Identifier'),
        ),
        migrations.AlterField(
            model_name='herocontent',
            name='description',
            field=models.TextField(default='Connect with thousands of verified local professionals for repairs, gardening, cleaning, and more. Quality guaranteed.'),
        ),
    ]
