# Generated by Django 6.0.1 on 2026-01-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_category_icon_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='internal_rating',
            field=models.FloatField(default=0.0, help_text='Average customer rating (0-5)'),
        ),
    ]
